# Generated by Django 5.1.3 on 2024-11-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('Phone', models.CharField(blank=True, max_length=200, null=True)),
                ('Password', models.CharField(blank=True, max_length=200, null=True)),
                ('CPassword', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
